/*
 * This file is generated by jOOQ.
 */
package lecturemanagementdoctor.doctor.Database.doctordb;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lecturemanagementdoctor.doctor.Database.doctordb.tables.Doctor;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doctordb extends SchemaImpl {

    private static final long serialVersionUID = 646444154;

    /**
     * The reference instance of <code>doctordb</code>
     */
    public static final Doctordb DOCTORDB = new Doctordb();

    /**
     * The table <code>doctordb.Doctor</code>.
     */
    public final Doctor DOCTOR = Doctor.DOCTOR;

    /**
     * No further instances allowed
     */
    private Doctordb() {
        super("doctordb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Doctor.DOCTOR);
    }
}
